# Nothing may reach the package tarball that gq did not decide to publish.
#
# R CMD build ships every top-level entry not excluded, so a directory added at
# the repo root lands in the library of anyone installing gq from GitHub. gq#76:
# .claude/ and gq.Rproj were doing exactly that, and R CMD check --as-cran had
# been reporting both as NOTEs.
#
# CLAUDE.md records this class finding 20 hits across 16 repos when it was last
# swept, and gq came back CLEAN on that sweep -- because the sweep looked for
# comms/ research/ planning/ dev/ by name, and .claude is none of them. A guard
# that enumerates the top level cannot go stale that way: it fails on ANYTHING
# undeclared, including the directory nobody has invented yet.

# ---------------------------------------------------------------------------
# What R excludes on its own, taken from R rather than from memory.
#
# `.gitignore` is absent from the tarball despite having no .Rbuildignore
# pattern, so a guard that models exclusion as "matched by .Rbuildignore" alone
# reports it as undeclared and fails on a correct tree. R applies three separate
# mechanisms, and these are its own objects, not a transcription of them:
#
#   get_exclude_patterns()   regexes prepended to .Rbuildignore's own lines
#                            (this is what excludes .Rbuildignore itself)
#   .vc_dir_names            .git, .svn, CVS, ... -- directories only
#   .hidden_file_exclusions  .gitignore, .Rprofile, .Rproj.user, ...
#
# Hardcoding the two entries this repo happens to have today (.git, .gitignore)
# would be the coincidental-scope defect CLAUDE.md describes: a literal set that
# matches the current data and silently stops covering anything new. Pinning to
# the source of truth is the documented remedy.
#
# Reading unexported objects is deliberate. They ARE the consumer's rules, and
# if a future R renames them this errors -- loudly, in the safe direction --
# rather than quietly excluding nothing. The test below asserts they are still
# there, so the failure names the cause.
r_auto_excluded <- function(entries, isdir) {
  if (!length(entries)) return(logical(0))

  pats <- tools:::get_exclude_patterns()
  by_pattern <- vapply(entries, function(e) {
    any(vapply(pats, function(p) grepl(p, e, perl = TRUE, ignore.case = TRUE),
               logical(1)))
  }, logical(1), USE.NAMES = FALSE)

  # Transcribed from tools:::.build_packages, restricted to the rules that can
  # apply to a TOP-LEVEL entry -- its src/ and inst/doc/ rules cannot.
  by_pattern |
    (isdir & entries %in% c("check", "chm", tools:::.vc_dir_names)) |
    (isdir & grepl("([Oo]ld|\\.Rcheck)$", entries)) |
    entries %in% c("Read-and-delete-me", "GNUMakefile") |
    startsWith(entries, "._") |
    entries %in% tools:::.hidden_file_exclusions
}

# Matched by one of the repo's OWN .Rbuildignore lines.
#
# Same call R makes: Perl regex, case-insensitive, and a PARTIAL match rather
# than an anchored one -- which is why every line in gq's .Rbuildignore carries
# ^...$. A pattern written without them would exclude far more than intended.
rbuildignore_excluded <- function(entries, patterns) {
  if (!length(entries)) return(logical(0))
  patterns <- patterns[nzchar(patterns)]
  vapply(entries, function(e) {
    any(vapply(patterns, function(p) grepl(p, e, perl = TRUE, ignore.case = TRUE),
               logical(1)))
  }, logical(1), USE.NAMES = FALSE)
}

# What gq intends to publish. Every one of these is on R's own `known`
# top-level list in tools:::.check_packages, which is why none of them NOTEs.
#
# This is an allowlist, not an exemption list: adding a name here says "gq ships
# this on purpose", and the test below fails if a name here has stopped
# existing, so a stale entry cannot sit unnoticed.
ships <- c(
  "DESCRIPTION", "NAMESPACE", "LICENSE", "NEWS.md", "README.md",
  "R", "data", "inst", "man", "tests", "vignettes"
)

# Generated by R CMD build / INSTALL into the tarball, absent from the source
# tree. Only meaningful in tarball mode below.
generated <- c("build", "MD5", "INDEX")

# The entries this guard exists to keep out. Named explicitly so tarball mode
# has something to assert even if `ships` were somehow over-broad.
forbidden <- c(".claude", "gq.Rproj")

# ---------------------------------------------------------------------------
# Locate the tree to inspect, and say which layout was found.
#
# Test for the .Rbuildignore FILE, never for a directory of the right name.
# test-vignette_legend_coverage.R in this suite carries the scar: its first
# version walked up looking for a `vignettes/` directory, matched an unrelated
# one in R CMD check's temp tree, reported "found", then died in readLines().
# Requiring DESCRIPTION to name gq is what makes a match evidence rather than a
# coincidence -- a stranger's package one level up satisfies neither.
#
# Two layouts reach real evidence, and they assert the same property from
# opposite ends:
#
#   source   devtools::test() from tests/testthat/. .Rbuildignore is present, so
#            every top-level entry can be classified. This is the mode that
#            catches a new directory at the moment it is added.
#   tarball  R CMD check unpacks the built package to <pkg>.Rcheck/00_pkg_src/gq
#            -- that tree IS the shipped artifact. It carries no .Rbuildignore
#            (verified: get_exclude_patterns() excludes it), so nothing can be
#            classified there; what CAN be asserted is that only declared
#            entries are present, which is the stronger claim anyway.
names_gq <- function(d) {
  f <- file.path(d, "DESCRIPTION")
  if (!file.exists(f)) return(FALSE)
  any(grepl("^Package:[[:space:]]*gq[[:space:]]*$", readLines(f, warn = FALSE)))
}

build_root <- function() {
  up <- c("..", "../..", "../../..")

  src <- up[file.exists(file.path(up, ".Rbuildignore")) &
              vapply(up, names_gq, logical(1))]
  if (length(src)) {
    return(list(mode = "source", path = normalizePath(src[[1]])))
  }

  shipped <- file.path(up, "00_pkg_src", "gq")
  hit <- shipped[vapply(shipped, names_gq, logical(1))]
  if (length(hit)) {
    return(list(mode = "tarball", path = normalizePath(hit[[1]])))
  }

  list(mode = NA_character_, path = NA_character_)
}

top_level <- function(path) {
  setdiff(list.files(path, all.files = TRUE, no.. = TRUE), c(".", ".."))
}

# ---------------------------------------------------------------------------

test_that("R still exposes the exclusion rules this guard is pinned to", {
  # If a future R renames or drops these, r_auto_excluded() errors and every
  # test below fails with a stack trace pointing at tools. This one names the
  # cause instead, so nobody goes looking in gq for the breakage.
  expect_type(tools:::get_exclude_patterns(), "character")
  expect_type(tools:::.vc_dir_names, "character")
  expect_type(tools:::.hidden_file_exclusions, "character")

  # And they still cover what gq relies on them covering. Without this the
  # lists could empty out and the guard would silently widen.
  expect_true(".git" %in% tools:::.vc_dir_names)
  expect_true(".gitignore" %in% tools:::.hidden_file_exclusions)
  expect_true(any(vapply(tools:::get_exclude_patterns(),
                         function(p) grepl(p, ".Rbuildignore", perl = TRUE,
                                           ignore.case = TRUE),
                         logical(1))))
})

test_that("every top-level entry is either shipped on purpose or excluded on purpose", {
  root <- build_root()

  skip_if(is.na(root$mode),
          paste("no gq tree found: expected a source checkout with",
                ".Rbuildignore, or R CMD check's 00_pkg_src/gq, within three",
                "levels of tests/testthat"))

  entries <- top_level(root$path)
  # A tree with nothing in it would pass every assertion below for nothing.
  expect_gt(length(entries), 5)

  if (identical(root$mode, "source")) {
    isdir <- dir.exists(file.path(root$path, entries))
    patterns <- readLines(file.path(root$path, ".Rbuildignore"), warn = FALSE)

    auto <- r_auto_excluded(entries, isdir)
    ignored <- rbuildignore_excluded(entries, patterns)

    # The classification must actually be doing work. If .Rbuildignore stopped
    # being read -- wrong path, empty file -- `ignored` goes all-FALSE and the
    # failure would read as "everything is undeclared" rather than "the guard
    # is broken".
    expect_gt(sum(ignored), 5)
    expect_gt(sum(auto), 0)

    unexplained <- entries[!auto & !ignored & !(entries %in% ships)]
    expect_equal(unexplained, character(0))

    # A name in `ships` that no longer exists is a decision nobody re-made.
    # NOT applied to .Rbuildignore patterns: ^Rplots\.pdf$, ^doc$ and ^Meta$
    # are transient build artifacts that legitimately do not exist.
    expect_equal(setdiff(ships, entries), character(0))
  } else {
    # The artifact itself. Anything here is in someone's library.
    expect_equal(setdiff(entries, c(ships, generated)), character(0))
    expect_equal(intersect(entries, forbidden), character(0))

    # No dot-file survived the build, whatever it is called.
    expect_equal(entries[startsWith(entries, ".")], character(0))
  }
})

test_that("the guard fires on an undeclared top-level entry", {
  # Restore the bug. gq#76 was exactly this shape: two entries that no
  # .Rbuildignore line matched, that R does not exclude on its own, and that
  # nobody had declared. Runs unconditionally on synthetic input, so the logic
  # is still exercised in a build where the test above can only skip.
  entries <- c("DESCRIPTION", "R", "man", "planning", ".git", ".gitignore",
               ".Rbuildignore", ".claude", "gq.Rproj")
  isdir <- c(FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE)
  patterns <- c("^planning$", "^CLAUDE\\.md$")

  auto <- r_auto_excluded(entries, isdir)
  ignored <- rbuildignore_excluded(entries, patterns)

  # R's own rules take .git, .gitignore and .Rbuildignore off the table --
  # by three different mechanisms, which is the reason this category exists.
  expect_true(all(auto[match(c(".git", ".gitignore", ".Rbuildignore"), entries)]))
  # ...and do NOT cover the two that shipped. If R ever did, gq#76 would not
  # have happened and this guard would be unnecessary.
  expect_false(any(auto[match(c(".claude", "gq.Rproj"), entries)]))

  expect_true(ignored[match("planning", entries)])
  # ^CLAUDE\.md$ matches nothing here, proving patterns are matched against the
  # entry rather than assumed to hit.
  expect_false(ignored[match("R", entries)])

  unexplained <- entries[!auto & !ignored & !(entries %in% ships)]
  expect_setequal(unexplained, c(".claude", "gq.Rproj"))

  # And the fix clears it, rather than the guard being unable to reach green.
  patterns_fixed <- c(patterns, "^\\.claude$", "^gq\\.Rproj$")
  ignored_fixed <- rbuildignore_excluded(entries, patterns_fixed)
  expect_equal(entries[!auto & !ignored_fixed & !(entries %in% ships)],
               character(0))
})

test_that("an .Rbuildignore pattern is matched the way R matches it", {
  # Partial, not anchored: R uses grepl() with no implicit ^$. A pattern
  # written without them excludes more than its author meant, and this is the
  # cheapest place to see that.
  expect_true(rbuildignore_excluded("planning", "plan"))
  expect_false(rbuildignore_excluded("planning", "^plan$"))
  # Case-insensitive, which is easy to forget when reading .Rbuildignore.
  expect_true(rbuildignore_excluded("CLAUDE.md", "^claude\\.md$"))
  # An empty line in .Rbuildignore must not match everything.
  expect_false(rbuildignore_excluded("R", c("", "^nope$")))
})
