# Data documentation for bundled spatial datasets
# Generated by data-raw/bittner_creek.R and data-raw/neexdzii_kwa.R

# -- Bittner Creek (Prince George area) --

#' Bittner Creek watershed boundary
#'
#' Watershed polygon for Bittner Creek near Prince George, BC (~56 km²).
#' Pulled from the BC Freshwater Atlas via fwapg.
#'
#' @format An `sf` data frame with 1 row and columns:
#'   \describe{
#'     \item{area_ha}{Watershed area in hectares}
#'     \item{geom}{Polygon geometry (WGS 84)}
#'   }
#' @source BC Freshwater Atlas via newgraph database
"bittner_wsd"

#' Bittner Creek stream network
#'
#' FWA stream segments within the Bittner Creek watershed (order >= 2).
#'
#' @format An `sf` data frame with columns:
#'   \describe{
#'     \item{gnis_name}{Stream name from BC geographic names}
#'     \item{stream_order}{Strahler stream order}
#'     \item{geom}{Linestring geometry (WGS 84)}
#'   }
#' @source BC Freshwater Atlas via newgraph database
"bittner_streams"

#' Bittner Creek lakes
#'
#' FWA lake polygons within the Bittner Creek watershed.
#'
#' @format An `sf` data frame with columns:
#'   \describe{
#'     \item{name}{Lake name from BC geographic names}
#'     \item{area_ha}{Lake area in hectares}
#'     \item{geom}{Polygon geometry (WGS 84)}
#'   }
#' @source BC Freshwater Atlas via newgraph database
"bittner_lakes"

#' Bittner Creek roads
#'
#' DRA road segments within expanded Bittner Creek watershed.
#'
#' @format An `sf` data frame with columns:
#'   \describe{
#'     \item{road_type}{Transport line type code (RH1, RA1, RA2, etc.)}
#'     \item{geom}{Linestring geometry (WGS 84)}
#'   }
#' @source BC Digital Road Atlas via newgraph database
"bittner_roads"

#' Bittner Creek railway
#'
#' Railway track segments within expanded Bittner Creek watershed.
#'
#' @format An `sf` data frame with columns:
#'   \describe{
#'     \item{track_classification}{Railway track classification}
#'     \item{geom}{Linestring geometry (WGS 84)}
#'   }
#' @source BC GBA Railway Tracks via newgraph database
"bittner_railway"

#' Bittner Creek PSCIS assessments
#'
#' Fish passage assessments from PSCIS within expanded Bittner Creek watershed.
#'
#' @format An `sf` data frame with columns:
#'   \describe{
#'     \item{stream_crossing_id}{PSCIS crossing identifier}
#'     \item{road_name}{Road name at crossing}
#'     \item{stream_name}{Stream name at crossing}
#'     \item{barrier_result_code}{Assessment result (BARRIER, PASSABLE, POTENTIAL, UNKNOWN)}
#'     \item{geom}{Point geometry (WGS 84)}
#'   }
#' @source PSCIS via newgraph database
"bittner_pscis"

# -- Neexdzii Kwa (Upper Bulkley, Johnny David to Richfield) --

#' Neexdzii Kwa subbasin watershed boundary
#'
#' Subbasin polygon on the Neexdzii Kwa (Upper Bulkley River) between
#' Johnny David Creek (downstream) and Richfield Creek (upstream) in the
#' traditional territory of the Wet'suwet'en. ~212 km².
#' Generated by watershed subtraction using fresh.
#'
#' @format An `sf` data frame with 1 row and polygon geometry (WGS 84).
#' @source BC Freshwater Atlas via newgraph database and fresh package
"neexdzii_wsd"

#' Neexdzii Kwa stream network
#'
#' FWA stream segments within the Neexdzii Kwa subbasin,
#' fetched via network query (not spatial clip).
#'
#' @format An `sf` data frame with columns including:
#'   \describe{
#'     \item{gnis_name}{Stream name from BC geographic names}
#'     \item{stream_order}{Strahler stream order}
#'     \item{geom}{Linestring geometry (WGS 84)}
#'   }
#' @source BC Freshwater Atlas via newgraph database and fresh package
"neexdzii_streams"

#' Neexdzii Kwa lakes
#'
#' FWA lake polygons matched by waterbody key on the stream network
#' within the Neexdzii Kwa subbasin.
#'
#' @format An `sf` data frame with polygon geometry (WGS 84).
#' @source BC Freshwater Atlas via newgraph database and fresh package
"neexdzii_lakes"

#' Neexdzii Kwa wetlands
#'
#' FWA wetland polygons matched by waterbody key on the stream network
#' within the Neexdzii Kwa subbasin.
#'
#' @format An `sf` data frame with polygon geometry (WGS 84).
#' @source BC Freshwater Atlas via newgraph database and fresh package
"neexdzii_wetlands"

#' Neexdzii Kwa roads
#'
#' DRA road segments clipped to the Neexdzii Kwa subbasin.
#'
#' @format An `sf` data frame with columns:
#'   \describe{
#'     \item{road_type}{Transport line type code (RH1, RA1, RA2, etc.)}
#'     \item{geom}{Linestring geometry (WGS 84)}
#'   }
#' @source BC Digital Road Atlas via newgraph database
"neexdzii_roads"

#' Neexdzii Kwa railway
#'
#' Railway track segments clipped to the Neexdzii Kwa subbasin.
#'
#' @format An `sf` data frame with columns:
#'   \describe{
#'     \item{track_name}{Railway track name}
#'     \item{geom}{Linestring geometry (WGS 84)}
#'   }
#' @source BC GBA Railway Tracks via newgraph database
"neexdzii_railway"

#' British Columbia boundary (simplified)
#'
#' Simplified BC provincial boundary for keymap inset context.
#'
#' @format An `sf` data frame with 1 row and polygon geometry (WGS 84).
#' @source BC Freshwater Atlas via newgraph database
"neexdzii_bc"

#' Bulkley and Morice watershed groups
#'
#' Watershed group polygons for BULK and MORR for keymap inset context.
#'
#' @format An `sf` data frame with columns:
#'   \describe{
#'     \item{watershed_group_code}{FWA watershed group code (BULK, MORR)}
#'     \item{geom}{Polygon geometry (WGS 84)}
#'   }
#' @source BC Freshwater Atlas via newgraph database
"neexdzii_wsg"
